import { StyleSheet } from "react-native";
import { Fonts, Colors } from '../../../themes';

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    padding: 5,
    paddingHorizontal: 15,
  },
  sectionHeader: {
    backgroundColor: Colors.lite_bg,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  sectionHeaderText: {
    fontSize: 14,
    fontFamily: Fonts.OpenSans500Medium,
    color: Colors.ui_dark_bg,
  },
  fixedButton: {
    backgroundColor: Colors.color_white,
    paddingHorizontal: 5,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    height: 70
  },
  uploadDoc: {
    padding: 20,
    borderColor: Colors.color_dark_gray,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 0
  },
  uploadDocHeader: {
    fontFamily: Fonts.OpenSans600SemiBold,
    textAlign: 'center',
    marginBottom: 10,
    color: Colors.ui_dark_bg,
  },
  uploadDocSubHeader: {
    textAlign: 'center',
    fontFamily: Fonts.OpenSans600SemiBold,
    fontSize: 10,
    color: Colors.color_gray,
  },
  backgroundContainerCover: {
    height: 150,
    width: '100%',
  },
  deleteImages: {
    position: 'absolute',
    right: -8,
    top: -8,
    backgroundColor: '#F17B7B',
    borderRadius: 100,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    width: 20,
    height: 21,
    zIndex: 2,
  },
  chips: {
    borderWidth: 1.2,
    padding: 5,
    borderRadius: 100,
    textAlign: 'center',
    fontSize: 14,
    // width: 140,
    fontFamily: Fonts.OpenSans400Regular,
    color: Colors.color_dark_gray,
    marginRight: 8,
    marginBottom: 10,
    paddingHorizontal: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  chipsGroup: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  noDataFound: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    height: 200,
    alignContent: 'center',
  },
  noDataFoundHeader: {
    color: Colors.dark_text_color,
    fontSize: 17,
    fontFamily: Fonts.OpenSans600SemiBold,
    marginTop: 5
  },
  noDataFoundSubHeader: {
    color: Colors.color_gray,
    fontSize: 11,
    fontFamily: Fonts.OpenSans600SemiBold,
  },
  uploadDoc: {
    padding: 20,
    borderColor: Colors.color_dark_gray,
    borderWidth: 1,
    borderStyle: 'dashed',
    marginTop: 10,
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadedDoc: {
    padding: 20,
    borderColor: Colors.color_dark_gray,
    borderWidth: 1,
    borderStyle: 'dashed',
    marginTop: 10,
    borderRadius: 8,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    fontFamily: Fonts.OpenSans600SemiBold
  },
  uploadDocHeader: {
    fontFamily: Fonts.OpenSans600SemiBold,
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 5,
    color: Colors.ui_dark_bg
  },
  uploadDocSubHeader: {
    textAlign: 'center',
    fontFamily: Fonts.OpenSans600SemiBold,
    fontSize: 10,
    color: Colors.color_gray
  },
  error: {
    color: '#dc3545',
    fontSize: 10,
    fontStyle: 'italic',
    textAlign: 'right',
    position: 'absolute',
    right: 0,
    bottom: -13,
  },
  deleteImages: {
    position: 'absolute',
    right: -2,
    top: -1,
    backgroundColor: '#F17B7B',
    borderRadius: 100,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    width: 20,
    height: 21,
    zIndex: 2,
  },
  deleteCards: {
    position: 'absolute',
    backgroundColor: '#F17B7B',
    borderRadius: 100,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    width: 20,
    height: 21,
    zIndex: 2,
    margin: 'auto',
    top: 8,
    bottom: 0,
    right: 8,
  },
  uploadedDocContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // marginVertical: -30
  },
  uploadedImgTextWidth: {
    width: '100%',
    color: Colors.color_dark_gray
  },
  centeredView: {
    alignItems: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
    height: '100%',
    marginTop: 'auto',
  },
  modalView: {
    position: 'absolute',
    bottom: 20,
    backgroundColor: 'white',
    borderRadius: 5,
    padding: 10,
    paddingHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '90%',
  },
  modalText: {
    marginTop: 5,
    color: Colors.ui_dark_bg,
    fontFamily: Fonts.poppins600SemiBold,
    fontSize: 18,
    textAlign: 'center',
  }
});

export default styles;
