import { Platform, StyleSheet } from "react-native";
import { Fonts, Colors } from '../../../themes';

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.color_white,
    paddingHorizontal: 15,
  },
  headerContainer: {
    padding: 20,
    paddingHorizontal: 15,
    justifyContent: 'center',
  },
  header: {
    color: Colors.color_white,
    fontFamily: Fonts.OpenSans700Bold,
    fontSize: 18,
  },
  languageList: {
    padding: 15,
    paddingTop: 0,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 20,
  },
  curve: {
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  connectBerger: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  connectBergerLabel: {
    color: Colors.color_black,
  },
  error: {
    color: '#dc3545',
    fontSize: 10,
    // fontStyle: 'italic',
    textAlign: 'right',
    fontFamily: Fonts.poppins400Regular,
    marginTop: 2,
  },
  gridItem: {
    margin: 0,
    // te
  },
  profilePicturePosition: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  underReview: {
    backgroundColor: '#D9D9D9',
    width: 28,
    height: 28,
    zIndex: 99,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    position: 'absolute',
    right: -25,
    top: -5,
    borderWidth: 2,
    borderColor: 'white',
  },
  generalInfoContainer: {
    marginBottom: 15,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'nowrap',
  },
  generalInfoHeader: {
    color: Colors.color_black,
    fontSize: 15,
    fontFamily: Fonts.OpenSans600SemiBold,
    textTransform: 'capitalize',
  },
  icon: {
    marginRight: 10,
    marginTop: 5,
  },
  groupingMember: {
    marginLeft: 20,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  teamMemberCount: {
    color: Colors.color_black,
    fontSize: 17,
    fontFamily: Fonts.OpenSans700Bold,
    marginLeft: 8,
  },
  labelInput: {
    color: Colors.color_black,
    fontFamily: Fonts.OpenSans600SemiBold,
    marginLeft: 5,
    fontSize: 12,
  },
  deleteCards: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    borderRadius: 100,
    color: '#F17B7B',
    width: 20,
    height: 21,
    zIndex: 2,
    margin: 'auto',
    top: 22,
    bottom: 0,
    right: 20,
  },
  dotContacts: {
    position: 'absolute',
    backgroundColor: 'transparent',
    borderRadius: 100,
    color: Colors.color_dark_gray,
    width: 30,
    height: 30,
    zIndex: 2,
    margin: 'auto',
    top: 0,
    bottom: 0,
    right: 5,
  },
  alignCenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  customInput: {
    width: '100%',
    fontSize: 15,
    color: Colors.color_black,
    borderWidth: 1,
    borderRadius: 8,
    paddingLeft: 20,
    height: 42,
  },
  fixedButton: {
    backgroundColor: Colors.color_white,
    paddingHorizontal: 5,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: -40,
  },
  footerContainer: {
    padding: 12,
    margin: 12,
    borderRadius: 12,
    backgroundColor: '#80f',
  },
  footerText: {
    textAlign: 'center',
    color: 'white',
    fontWeight: '800',
  },
  langCard: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    margin: 5,
    padding: 10,
    paddingVertical: 20,
    borderRadius: 10,
    // borderWidth: 0.9,
    backgroundColor: 'white',
    // borderColor: Colors.color_light_gray,
    shadowColor: Colors.shadow_light,
    elevation: 10,
  },
  isCheck: {
    position: 'absolute',
    right: 0,
    top: -15,
    width: 24,
    height: 24,
  },
  title: {
    color: Colors.color_black,
    fontFamily: Fonts.poppins600SemiBold,
    fontSize: 18,
    letterSpacing: 0.18,
  },
  subTitle: {
    color: Colors.color_black,
    fontFamily: Fonts.OpenSans400Regular,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: 'rgba(52, 52, 52, 0.5)',
  },
  modalView: {
    backgroundColor: 'white',
    borderRadius: 5,
    padding: 10,
    paddingHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: Platform.OS === 'android' ? '97%' : '90%',
  },
  modalText: {
    marginBottom: 15,
    marginTop: 5,
    color: Colors.ui_dark_bg,
    fontFamily: Fonts.poppins600SemiBold,
    fontSize: 18,
  },
  modalOptionText: {
    marginBottom: 15,
    color: '#000',
    fontSize: 16,
    fontFamily: Fonts.poppins400Regular,
  },
  fixedButton: {
    backgroundColor: Colors.color_white,
    padding: 5,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  container: {
    backgroundColor: '#fff',
    padding: 5,
    paddingHorizontal: 15,
  },
  sectionHeader: {
    backgroundColor: Colors.lite_bg,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  sectionHeaderText: {
    fontSize: 14,
    fontFamily: Fonts.OpenSans500Medium,
    color: Colors.ui_dark_bg,
  },
  uploadDoc: {
    padding: 20,
    borderColor: Colors.color_dark_gray,
    borderWidth: 1,
    borderStyle: 'dashed',
    marginTop: 5,
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundContainerCover: {
    height: 150,
    width: '100%',
  },
  chips: {
    borderWidth: 1.2,
    padding: 5,
    borderRadius: 100,
    textAlign: 'center',
    fontSize: 14,
    // width: 140,
    fontFamily: Fonts.OpenSans400Regular,
    color: Colors.color_dark_gray,
    marginRight: 8,
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  chipsGroup: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  docURL: {
    width: 190,
    color: Colors.color_gray,
    fontSize: 12,
    fontFamily: Fonts.OpenSans600SemiBold
  },
  docUniqueNo: {
    fontFamily: Fonts.OpenSans600SemiBold,
    width: 160,
  },
  docNumber: {
    fontFamily: Fonts.OpenSans600SemiBold,
    color: Colors.ui_dark_bg,
  },
  docInfoGroup: {
    width: '70%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  docImage: {
    height: 80,
    width: 80,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  docContainer: {
    flexDirection: 'row',
    width: '100%',
    margin: 10,
    alignContent: 'center',
    alignItems: 'center',
  },
  kycSuccessStatus: {
    borderWidth: 1.2,
    padding: 5,
    borderRadius: 100,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: Fonts.OpenSans400Regular,
    marginRight: 8,
    marginBottom: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    backgroundColor: 'rgba(38, 192, 13, 0.25)',
    borderColor: '#rgba(38, 192, 13, 1)',
  },
  kycRejectStatus: {
    borderWidth: 1.2,
    padding: 5,
    borderRadius: 100,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: Fonts.OpenSans400Regular,
    marginRight: 8,
    marginBottom: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    backgroundColor: '#F17B7B',
    borderColor: '#9C0000',
  },
  kycPendingStatus: {
    borderWidth: 1.2,
    padding: 5,
    borderRadius: 100,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: Fonts.OpenSans400Regular,
    marginRight: 8,
    marginBottom: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    backgroundColor: '#FFEB89',
    borderColor: '#FFEB89',
  },
  statusGroup: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 10
  },
  kycReject: {
    color: Colors.color_dark_red,
    fontFamily: Fonts.poppins500Medium,
    fontSize: 12
  },
  kycMismatch: {
    fontFamily: Fonts.poppins500Medium,
    fontSize: 12,
    color: Colors.color_yellow
  },
  errorOtp: {
    color: '#dc3545',
    fontSize: 10,
    fontStyle: 'italic',
    textAlign: 'right',
    position: 'absolute',
    fontFamily: Fonts.poppins400Regular,
    right: 10,
    bottom: 0,
  },
});

export default styles;
